import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import "bootstrap/dist/css/bootstrap.min.css"; // Thêm dòng này
import Header from "./component/header";
import Footer from "./component/footer";
import '@fortawesome/fontawesome-free/css/all.min.css';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <script src="https://unpkg.com/react/umd/react.development.js"></script>
          <script src="https://unpkg.com/react-dom/umd/react-dom.development.js"></script>
          <script src="https://unpkg.com/@babel/standalone/babel.js"></script>
          <script src="https://cdn.tailwindcss.com"></script>
          <Link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
      {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"></link> */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ backgroundColor: 'var(--background)' }}>

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
